SKYOPS-33566 - move featuregenerator up - sling initial content conversion
adobe/aemanalyser-maven-plugin pull request #165
Opened 2022-07-22 07:43 UTC by niekraaijmakers

Making it possible to pass down the featuregenerator to converter / aggregator
This to grant access to the features in the converter - so it can read an extension it needs
Lazy load mechanism so the features are only parsed 1 time (expensive operation)

Also invoking cpconvert with sling initial content - EXTRACT_AND_REMOVE > putting in a separate folder

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-28 16:16 UTC, bosschaert commented
@niekraaijmakers Maybe make this a draft PR if it's still work in progress?

2022-08-23 11:12 UTC, niekraaijmakers commented
@bosschaert @cziegeler ready for review

2022-08-24 07:47 UTC, niekraaijmakers commented
@karlpauls  @rombert please help out :)

2022-08-24 07:51 UTC, rombert requested changes
Overall LGTM, some minor needs. It would be good to for someone else more familiar with the codebase to review as well.

One things which I would like to ask is to create an issue in _this_ project describing the change. We don't know what this SKYOPS thing is :-)

2022-08-24 07:51 UTC, rombert commented on aemanalyser-core/src/main/java/com/adobe/aem/analyser/AemPackageConverter.java
> +                    .setAclManager(
Do you need to set defaults here?

2022-08-24 07:51 UTC, rombert commented on aemanalyser-core/src/main/java/com/adobe/aem/analyser/AemPackageConverter.java
> +                            new DefaultIndexManager()
Do you need to set defaults here?

2022-08-24 07:51 UTC, rombert commented on aemanalyser-core/src/main/java/com/adobe/aem/analyser/AemPackageConverter.java
> +            if ( !mutableContentPackagesWithRunMode.isEmpty() ) {
You don't need this empty check here.

2022-08-24 07:56 UTC, niekraaijmakers commented on aemanalyser-core/src/main/java/com/adobe/aem/analyser/AemPackageConverter.java
> +                            new DefaultIndexManager()
yes

2022-08-24 07:56 UTC, niekraaijmakers commented on aemanalyser-core/src/main/java/com/adobe/aem/analyser/AemPackageConverter.java
> +                    .setAclManager(
yes

2022-08-24 08:18 UTC, rombert approved these changes
LGTM, thanks.

2022-08-24 08:29 UTC, bosschaert approved these changes

2022-08-24 08:33 UTC, merged